conversation: {}

# The Hugging Face model name of the base model.
#base_model: meta-llama/Meta-Llama-3-8B-Instruct 
base_model: meta-llama/Meta-Llama-3-8B-Instruct

# adjust hyperparameters
epochs: 2
learning_rate: 0.0002
lora_rank: 32
batch_size: 8
evaluation_split: 0